spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unide_db?serverTimezone=Asia/Seoul
    username: ${UNIDE_DB_USERNAME}
    password: ${UNIDE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.zoho.com
    port: 587
    username: ${ZOHO_MAIL_USERNAME}
    password: ${ZOHO_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true